name: docker release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - 'LICENSE'
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - 'LICENSE'
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
    publish-docker-images:
      name: Push Docker images to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Get version info
          id: get_version
          run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./docker/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKER_HUB_USERNAME }}/kun-visual-novel:${{ steps.get_version.outputs.VERSION }}
              ${{ secrets.DOCKER_HUB_USERNAME }}/kun-visual-novel:latest
            platforms: linux/amd64,linux/arm64
            cache-from: type=gha,scope=${{ github.workflow }}
            cache-to: type=gha,mode=max,scope=${{ github.workflow }}
